// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/index.qtpl:1
package templates

//line templates/index.qtpl:1
import "github.com/Goryudyuma/ishoconkstm2021gw/webapp/go/types"

//line templates/index.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index.qtpl:2
func StreamIndex(qw422016 *qt422016.Writer, currentUser types.User, products []types.ProductWithComments) {
//line templates/index.qtpl:2
	qw422016.N().S(`
`)
//line templates/index.qtpl:3
	streamheader(qw422016, currentUser)
//line templates/index.qtpl:3
	qw422016.N().S(`
<div class="jumbotron">
  <div class="container">
    <h1>今日は大安売りの日です！</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    `)
//line templates/index.qtpl:11
	for _, product := range products {
//line templates/index.qtpl:11
		qw422016.N().S(`
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="/products/`)
//line templates/index.qtpl:15
		qw422016.N().D(product.ID)
//line templates/index.qtpl:15
		qw422016.N().S(`">`)
//line templates/index.qtpl:15
		qw422016.E().S(product.Name)
//line templates/index.qtpl:15
		qw422016.N().S(`</a>
          </div>
          <div class="panel-body">
            <a href="/products/`)
//line templates/index.qtpl:18
		qw422016.N().D(product.ID)
//line templates/index.qtpl:18
		qw422016.N().S(`"><img src="`)
//line templates/index.qtpl:18
		qw422016.E().S(product.ImagePath)
//line templates/index.qtpl:18
		qw422016.N().S(`" class="img-responsive" /></a>
            <h4>価格</h4>
            <p>`)
//line templates/index.qtpl:20
		qw422016.N().D(product.Price)
//line templates/index.qtpl:20
		qw422016.N().S(`円</p>
            <h4>商品説明</h4>
            <p>`)
//line templates/index.qtpl:22
		qw422016.E().S(product.Description)
//line templates/index.qtpl:22
		qw422016.N().S(`</p>
            <h4>`)
//line templates/index.qtpl:23
		qw422016.N().D(product.CommentCount)
//line templates/index.qtpl:23
		qw422016.N().S(`件のレビュー</h4>
            <ul>
              `)
//line templates/index.qtpl:25
		for _, cw := range product.Comments {
//line templates/index.qtpl:25
			qw422016.N().S(`
                <li>`)
//line templates/index.qtpl:26
			qw422016.E().S(cw.Content)
//line templates/index.qtpl:26
			qw422016.N().S(` by `)
//line templates/index.qtpl:26
			qw422016.E().S(cw.Writer)
//line templates/index.qtpl:26
			qw422016.N().S(`</li>
              `)
//line templates/index.qtpl:27
		}
//line templates/index.qtpl:27
		qw422016.N().S(`
            </ul>
          </div>
          `)
//line templates/index.qtpl:30
		if currentUser.ID > 0 {
//line templates/index.qtpl:30
			qw422016.N().S(`
            <div class="panel-footer">
              <form method="POST" action="/products/buy/`)
//line templates/index.qtpl:32
			qw422016.N().D(product.ID)
//line templates/index.qtpl:32
			qw422016.N().S(`">
                <fieldset>
                  <input class="btn btn-success btn-block" type="submit" name="buy" value="購入" />
                </fieldset>
              </form>
            </div>
          `)
//line templates/index.qtpl:38
		}
//line templates/index.qtpl:38
		qw422016.N().S(`
        </div>
      </div>
    `)
//line templates/index.qtpl:41
	}
//line templates/index.qtpl:41
	qw422016.N().S(`
  </div>
</div>
`)
//line templates/index.qtpl:44
	streamfooter(qw422016)
//line templates/index.qtpl:44
	qw422016.N().S(`
`)
//line templates/index.qtpl:45
}

//line templates/index.qtpl:45
func WriteIndex(qq422016 qtio422016.Writer, currentUser types.User, products []types.ProductWithComments) {
//line templates/index.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:45
	StreamIndex(qw422016, currentUser, products)
//line templates/index.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:45
}

//line templates/index.qtpl:45
func Index(currentUser types.User, products []types.ProductWithComments) string {
//line templates/index.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:45
	WriteIndex(qb422016, currentUser, products)
//line templates/index.qtpl:45
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:45
	return qs422016
//line templates/index.qtpl:45
}
