// Code generated by qtc from "layout.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/layout.qtpl:1
package templates

//line templates/layout.qtpl:1
import "github.com/Goryudyuma/ishoconkstm2021gw/webapp/go/types"

//line templates/layout.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/layout.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/layout.qtpl:2
func streamheader(qw422016 *qt422016.Writer, currentUser types.User) {
//line templates/layout.qtpl:2
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html" charset="utf-8">
<link rel="stylesheet" href="/css/bootstrap.min.css">
<title>すごいECサイト</title>
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">すごいECサイトで爆買いしよう!</a>
    </div>
    <div class="header clearfix">
    `)
//line templates/layout.qtpl:18
	if currentUser.ID != 0 {
//line templates/layout.qtpl:18
		qw422016.N().S(`
      <nav>
        <ul class="nav nav-pills pull-right">
          <li role="presentation"><a href="/users/`)
//line templates/layout.qtpl:21
		qw422016.N().D(currentUser.ID)
//line templates/layout.qtpl:21
		qw422016.N().S(`">`)
//line templates/layout.qtpl:21
		qw422016.E().S(currentUser.Name)
//line templates/layout.qtpl:21
		qw422016.N().S(`さんの購入履歴</a></li>
          <li role="presentation"><a href="/logout">Logout</a></li>
        </ul>
      </nav>
    `)
//line templates/layout.qtpl:25
	} else {
//line templates/layout.qtpl:25
		qw422016.N().S(`
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation"><a href="/login">Login</a></li>
      </ul>
    </nav>
    `)
//line templates/layout.qtpl:31
	}
//line templates/layout.qtpl:31
	qw422016.N().S(`
  </div>
</nav>

`)
//line templates/layout.qtpl:35
}

//line templates/layout.qtpl:35
func writeheader(qq422016 qtio422016.Writer, currentUser types.User) {
//line templates/layout.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/layout.qtpl:35
	streamheader(qw422016, currentUser)
//line templates/layout.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line templates/layout.qtpl:35
}

//line templates/layout.qtpl:35
func header(currentUser types.User) string {
//line templates/layout.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/layout.qtpl:35
	writeheader(qb422016, currentUser)
//line templates/layout.qtpl:35
	qs422016 := string(qb422016.B)
//line templates/layout.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/layout.qtpl:35
	return qs422016
//line templates/layout.qtpl:35
}

//line templates/layout.qtpl:36
func streamfooter(qw422016 *qt422016.Writer) {
//line templates/layout.qtpl:36
	qw422016.N().S(`

</body>
</html>
`)
//line templates/layout.qtpl:40
}

//line templates/layout.qtpl:40
func writefooter(qq422016 qtio422016.Writer) {
//line templates/layout.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/layout.qtpl:40
	streamfooter(qw422016)
//line templates/layout.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line templates/layout.qtpl:40
}

//line templates/layout.qtpl:40
func footer() string {
//line templates/layout.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/layout.qtpl:40
	writefooter(qb422016)
//line templates/layout.qtpl:40
	qs422016 := string(qb422016.B)
//line templates/layout.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/layout.qtpl:40
	return qs422016
//line templates/layout.qtpl:40
}
