// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/login.qtpl:1
package templates

//line templates/login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/login.qtpl:1
func StreamLogin(qw422016 *qt422016.Writer, message string) {
//line templates/login.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html" charset="utf-8">
<link rel="stylesheet" href="/css/bootstrap.min.css">
<title>すごいECサイト</title>
</head>
<body class="container">
  <h1 class="jumbotron"><a href="/">すごいECサイト</a></h1>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="text-danger" id="logout-message">`)
//line templates/login.qtpl:14
	qw422016.E().S(message)
//line templates/login.qtpl:14
	qw422016.N().S(`</div>
        <div class="login-panel panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Sign In</h3>
          </div>
          <div class="panel-body">
            <form method="POST" action="/login">
              <fieldset>
                <div class="form-group">
                  <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>
                </div>
                <div class="form-group">
                  <input class="form-control" placeholder="Password" name="password" type="password" value="">
                </div>
                <!-- Change this to a button or input when using this as a form -->
                <input class="btn btn-lg btn-success btn-block" type="submit" name="Login" value="Login" />
              </fieldset>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
`)
//line templates/login.qtpl:39
}

//line templates/login.qtpl:39
func WriteLogin(qq422016 qtio422016.Writer, message string) {
//line templates/login.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/login.qtpl:39
	StreamLogin(qw422016, message)
//line templates/login.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line templates/login.qtpl:39
}

//line templates/login.qtpl:39
func Login(message string) string {
//line templates/login.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/login.qtpl:39
	WriteLogin(qb422016, message)
//line templates/login.qtpl:39
	qs422016 := string(qb422016.B)
//line templates/login.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/login.qtpl:39
	return qs422016
//line templates/login.qtpl:39
}
