// Code generated by qtc from "mypage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/mypage.qtpl:1
package templates

//line templates/mypage.qtpl:1
import "github.com/Goryudyuma/ishoconkstm2021gw/webapp/go/types"

//line templates/mypage.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/mypage.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/mypage.qtpl:2
func StreamMyPage(qw422016 *qt422016.Writer, currentUser types.User, user types.User, products []types.Product, totalPay int) {
//line templates/mypage.qtpl:2
	qw422016.N().S(`
`)
//line templates/mypage.qtpl:3
	streamheader(qw422016, currentUser)
//line templates/mypage.qtpl:3
	qw422016.N().S(`
<div class="jumbotron">
  <div class="container">
    <h2>`)
//line templates/mypage.qtpl:6
	qw422016.E().S(user.Name)
//line templates/mypage.qtpl:6
	qw422016.N().S(` さんの購入履歴</h2>
    <h4>合計金額: `)
//line templates/mypage.qtpl:7
	qw422016.N().D(totalPay)
//line templates/mypage.qtpl:7
	qw422016.N().S(`円</h4>
  </div>
</div>
<div class="container">
  <div class="row">
    `)
//line templates/mypage.qtpl:12
	for _, product := range products {
//line templates/mypage.qtpl:12
		qw422016.N().S(`
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <a href="/products/`)
//line templates/mypage.qtpl:16
		qw422016.N().D(product.ID)
//line templates/mypage.qtpl:16
		qw422016.N().S(`">`)
//line templates/mypage.qtpl:16
		qw422016.E().S(product.Name)
//line templates/mypage.qtpl:16
		qw422016.N().S(`</a>
          </div>
          <div class="panel-body">
            <a href="/products/`)
//line templates/mypage.qtpl:19
		qw422016.N().D(product.ID)
//line templates/mypage.qtpl:19
		qw422016.N().S(`"><img src="`)
//line templates/mypage.qtpl:19
		qw422016.E().S(product.ImagePath)
//line templates/mypage.qtpl:19
		qw422016.N().S(`" class="img-responsive" /></a>
            <h4>価格</h4>
            <p>`)
//line templates/mypage.qtpl:21
		qw422016.N().D(product.Price)
//line templates/mypage.qtpl:21
		qw422016.N().S(`円</p>
            <h4>商品説明</h4>
            <p>`)
//line templates/mypage.qtpl:23
		qw422016.E().S(product.Description)
//line templates/mypage.qtpl:23
		qw422016.N().S(`</p>
            <h4>購入日時</h4>
            <p>`)
//line templates/mypage.qtpl:25
		qw422016.E().S(product.CreatedAt)
//line templates/mypage.qtpl:25
		qw422016.N().S(`</p>
          </div>
          `)
//line templates/mypage.qtpl:27
		if user.ID == currentUser.ID {
//line templates/mypage.qtpl:27
			qw422016.N().S(`
            <div class="panel-footer">
              <form method="POST" action="/comments/`)
//line templates/mypage.qtpl:29
			qw422016.N().D(product.ID)
//line templates/mypage.qtpl:29
			qw422016.N().S(`">
                <fieldset>
                  <div class="form-group">
                    <input class="form-control" placeholder="Comment Here" name="content" value="">
                  </div>
                  <input class="btn btn-success btn-block" type="submit" name="send_comment" value="コメントを送信" />
                </fieldset>
              </form>
            </div>
          `)
//line templates/mypage.qtpl:38
		}
//line templates/mypage.qtpl:38
		qw422016.N().S(`
        </div>
      </div>
    `)
//line templates/mypage.qtpl:41
	}
//line templates/mypage.qtpl:41
	qw422016.N().S(`
  </div>
</div>
`)
//line templates/mypage.qtpl:44
	streamfooter(qw422016)
//line templates/mypage.qtpl:44
	qw422016.N().S(`
`)
//line templates/mypage.qtpl:45
}

//line templates/mypage.qtpl:45
func WriteMyPage(qq422016 qtio422016.Writer, currentUser types.User, user types.User, products []types.Product, totalPay int) {
//line templates/mypage.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mypage.qtpl:45
	StreamMyPage(qw422016, currentUser, user, products, totalPay)
//line templates/mypage.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line templates/mypage.qtpl:45
}

//line templates/mypage.qtpl:45
func MyPage(currentUser types.User, user types.User, products []types.Product, totalPay int) string {
//line templates/mypage.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mypage.qtpl:45
	WriteMyPage(qb422016, currentUser, user, products, totalPay)
//line templates/mypage.qtpl:45
	qs422016 := string(qb422016.B)
//line templates/mypage.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mypage.qtpl:45
	return qs422016
//line templates/mypage.qtpl:45
}
